<a href="https://colab.research.google.com/github/VaibhaviDeveloper/MSIS_AML/blob/main/AML_Lab_BiasVariance_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [3]:
import os
os.listdir('/content/drive/MyDrive')

['Colab Notebooks',
 'data-1.csv',
 'Kaagaz_20220914_141308009993.pdf',
 'Kaagaz_20220914_141308009993.gdoc',
 'Untitled presentation (4).gslides',
 'Untitled presentation (3).gslides',
 'Untitled presentation (2).gslides',
 'Untitled presentation (1).gslides',
 'Untitled presentation.gslides',
 'Untitled form (1).gform',
 'Untitled form.gform',
 'AmazonLogo.jpg',
 'SignIn.jpg',
 'E-Commerce.html',
 'SignUp.html',
 'SignIn.html',
 'Forgot.html',
 'Successful.html',
 'style (1).css',
 'StripLight.jpg',
 'hero-img.jpg',
 'style2.css',
 'Laptop.jpg',
 'Smartwatch.jpg',
 'RoomFreshner.jpg',
 'signup.html',
 'signin.html',
 'forgot.html',
 'twoa.html',
 'styletwo.css',
 'style.css',
 'successfull.html',
 'AmazonImage.jpg',
 'ScrollinBlinking.html',
 "Vaibhavi's Resume.pdf",
 "Vaibhavi's Resume (1).gdoc",
 "Vaibhavi's Resume.gdoc",
 'nnm22cs195.pdf',
 'Vaibhavi N-Resume (3).pdf',
 'Sambhram Permission.gdoc',
 'Vaibhavi N-Resume (1).pdf',
 'Vaibhavi N-Resume.pdf',
 'Classroom',
 'archive (8)',
 'Patent APPLICATION FORM.docx',
 'Final_Year_Project (1).gdoc',
 'Vaibhavi N-Resume (2).pdf',
 'Vaibhavi N-Resume (2)-1.pdf',
 'Photoshoot 25',
 'Intern Information Form.docx',
 '36101.jpg',
 'Miniproject_MSIS_papers.docx',
 'bestsellers with categories.csv',
 'Data.csv',
 'Groceries_dataset.csv',
 'Copy of bestsellers with categories.csv',
 'Iris.csv',
 'diabetes.csv',
 'Social_Network_Ads.csv',
 'adult.csv',
 'Salary_Data.csv',
 'Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv',
 'Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv',
 'Friday-WorkingHours-Morning.pcap_ISCX.csv',
 'Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv',
 'Monday-WorkingHours.pcap_ISCX.csv',
 'Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv',
 'Tuesday-WorkingHours.pcap_ISCX.csv',
 'Wednesday-workingHours.pcap_ISCX.csv',
 'teleCust.csv',
 'WA_Fn-UseC_-Telco-Customer-Churn.csv',
 'application_train (1).csv',
 'application_train.csv',
 'AML.gdoc',
 'MiniProjectLiteratureReview.gdoc']

In [4]:
data = pd.read_csv('/content/drive/MyDrive/data-1.csv')

In [5]:
data.head()

   offer  Age  online payment  items
0      1   35               0      5
1      1   26               0      4
2      1   41               0      9
3      1   34               0     10
4      1   38               0      3

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error

In [7]:
from sklearn.feature_selection import VarianceThreshold

In [11]:
selector = VarianceThreshold(threshold=0.0)
X_selected = selector.fit_transform(data)
selected_columns = data.columns[selector.get_support()]
print("Selected Columns:",list(selected_columns))

Selected Columns: ['Age', 'items']

In [13]:
data2 = pd.read_csv('/content/drive/MyDrive/data-2.csv')

In [14]:
selector = VarianceThreshold(threshold=0.0)
X_selected = selector.fit_transform(data2)
selected_columns = data2.columns[selector.get_support()]
print("Selected Columns:",list(selected_columns))

Selected Columns: ['referred', 'repeat', 'Age', 'Promoted', 'items']

In [15]:
data2.head()

   referred  repeat  Age  Promoted  items
0         1       0   35         1      5
1         0       0   26         0      4
2         1       0   41         1      9
3         1       1   34         0     10
4         1       0   38         1      3

In [19]:
selector = VarianceThreshold(threshold=0.5)
X_selected = selector.fit_transform(data2)
selected_columns = data2.columns[selector.get_support()]
print("Selected Columns:",list(selected_columns))

Selected Columns: ['Age', 'items']