<a href="https://colab.research.google.com/github/VaibhaviDeveloper/MSIS_AML/blob/main/DecisionTree2Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
os.listdir('/content/drive/MyDrive')

['Colab Notebooks',
 'Kaagaz_20220914_141308009993.pdf',
 'Kaagaz_20220914_141308009993.gdoc',
 'Untitled presentation (4).gslides',
 'Untitled presentation (3).gslides',
 'Untitled presentation (2).gslides',
 'Untitled presentation (1).gslides',
 'Untitled presentation.gslides',
 'Untitled form (1).gform',
 'Untitled form.gform',
 'AmazonLogo.jpg',
 'SignIn.jpg',
 'E-Commerce.html',
 'SignUp.html',
 'SignIn.html',
 'Forgot.html',
 'Successful.html',
 'style (1).css',
 'StripLight.jpg',
 'hero-img.jpg',
 'style2.css',
 'Laptop.jpg',
 'Smartwatch.jpg',
 'RoomFreshner.jpg',
 'signup.html',
 'signin.html',
 'forgot.html',
 'twoa.html',
 'styletwo.css',
 'style.css',
 'successfull.html',
 'AmazonImage.jpg',
 'ScrollinBlinking.html',
 "Vaibhavi's Resume.pdf",
 "Vaibhavi's Resume (1).gdoc",
 "Vaibhavi's Resume.gdoc",
 'nnm22cs195.pdf',
 'Vaibhavi N-Resume (3).pdf',
 'Sambhram Permission.gdoc',
 'Vaibhavi N-Resume (1).pdf',
 'Vaibhavi N-Resume.pdf',
 'Classroom',
 'archive (8)',
 'Patent APPLICATION FORM.docx',
 'Final_Year_Project (1).gdoc',
 'Vaibhavi N-Resume (2).pdf',
 'Vaibhavi N-Resume (2)-1.pdf',
 'Photoshoot 25',
 'Intern Information Form.docx',
 '36101.jpg',
 'Miniproject_MSIS_papers.docx',
 'bestsellers with categories.csv',
 'Data.csv',
 'Copy of bestsellers with categories.csv',
 'Iris.csv',
 'Social_Network_Ads.csv']

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        1
1   2            4.9           3.0            1.4           0.2        1
2   3            4.7           3.2            1.3           0.2        1
3   4            4.6           3.1            1.5           0.2        1
4   5            5.0           3.6            1.4           0.2        1

In [ ]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species            int64
dtype: object

In [ ]:
null_num = df.isnull().sum()
null_num

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
df.drop(columns=["Id"],inplace=True)

In [ ]:
df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        1
1            4.9           3.0            1.4           0.2        1
2            4.7           3.2            1.3           0.2        1
3            4.6           3.1            1.5           0.2        1
4            5.0           3.6            1.4           0.2        1

In [ ]:
df.duplicated().sum()

np.int64(3)

In [ ]:
df[df.duplicated()]

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
34             4.9           3.1            1.5           0.1        1
37             4.9           3.1            1.5           0.1        1
142            5.8           2.7            5.1           1.9        2

In [ ]:
X=df.drop(columns=["Species"])
y=df["Species"]

In [ ]:
X

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [ ]:
y

0      1
1      1
2      1
3      1
4      1
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
22             4.6           3.6            1.0           0.2
15             5.7           4.4            1.5           0.4
65             6.7           3.1            4.4           1.4
11             4.8           3.4            1.6           0.2
42             4.4           3.2            1.3           0.2
..             ...           ...            ...           ...
71             6.1           2.8            4.0           1.3
106            4.9           2.5            4.5           1.7
14             5.8           4.0            1.2           0.2
92             5.8           2.6            4.0           1.2
102            7.1           3.0            5.9           2.1

[120 rows x 4 columns]

In [ ]:
X_test

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
73             6.1           2.8            4.7           1.2
18             5.7           3.8            1.7           0.3
118            7.7           2.6            6.9           2.3
78             6.0           2.9            4.5           1.5
76             6.8           2.8            4.8           1.4
31             5.4           3.4            1.5           0.4
64             5.6           2.9            3.6           1.3
141            6.9           3.1            5.1           2.3
68             6.2           2.2            4.5           1.5
82             5.8           2.7            3.9           1.2
110            6.5           3.2            5.1           2.0
12             4.8           3.0            1.4           0.1
36             5.5           3.5            1.3           0.2
9              4.9           3.1            1.5           0.1
19             5.1           3.8            1.5           0.3
56             6.3           3.3            4.7           1.6
104            6.5           3.0            5.8           2.2
69             5.6           2.5            3.9           1.1
55             5.7           2.8            4.5           1.3
132            6.4           2.8            5.6           2.2
29             4.7           3.2            1.6           0.2
127            6.1           3.0            4.9           1.8
26             5.0           3.4            1.6           0.4
128            6.4           2.8            5.6           2.1
131            7.9           3.8            6.4           2.0
145            6.7           3.0            5.2           2.3
108            6.7           2.5            5.8           1.8
143            6.8           3.2            5.9           2.3
45             4.8           3.0            1.4           0.3
30             4.8           3.1            1.6           0.2

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier()
classifier.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred=classifier.predict(X_test)
y_pred

array([0, 1, 2, 0, 0, 1, 0, 2, 0, 0, 2, 1, 1, 1, 1, 0, 2, 0, 0, 2, 1, 2,
       1, 2, 2, 2, 2, 2, 1, 1])

In [ ]:
y_test

73     0
18     1
118    2
78     0
76     0
31     1
64     0
141    2
68     0
82     0
110    2
12     1
36     1
9      1
19     1
56     0
104    2
69     0
55     0
132    2
29     1
127    2
26     1
128    2
131    2
145    2
108    2
143    2
45     1
30     1
Name: Species, dtype: int64

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_test,y_pred)
cm

array([[ 9,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 11]])

In [ ]:
accuracy=accuracy_score(y_test,y_pred)
print(accuracy*100)

100.0

In [ ]:
cr=classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30